M48
; DRILL file {KiCad (7.0.0-0)} date Thursday, April 20, 2023 at 01:26:38 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-20T13:26:38-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X4.6017Y-3.6634
X4.6017Y-3.8366
T2
X4.8307Y-3.2441
X6.7283Y-2.4567
T0
M30
